# Generated by Django 3.2.19 on 2023-06-27 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinemasite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='slug',
        ),
    ]
