# Generated by Django 3.2.19 on 2023-07-11 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinemasite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='filmtitle',
        ),
    ]
