# Generated by Django 3.2.19 on 2023-07-11 07:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemasite', '0002_remove_booking_filmtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='numoftickets',
            field=models.IntegerField(error_messages={'invalid': 'your custom error message'}, validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(1)], verbose_name='Number of tickets'),
        ),
    ]
