# Generated by Django 3.2.19 on 2023-06-30 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinemasite', '0002_auto_20230630_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
