# Generated by Django 3.2.19 on 2023-07-06 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinemasite', '0002_auto_20230706_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='fk',
        ),
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filmdate', to='cinemasite.filmshowtime', to_field='rundate'),
        ),
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filmtime', to='cinemasite.filmshowtime', to_field='runtime', verbose_name='Runtime'),
        ),
    ]
