# Generated by Django 3.2.19 on 2023-06-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemasite', '0002_remove_film_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='cast',
            field=models.TextField(max_length=500),
        ),
    ]
