# Generated by Django 3.2.19 on 2023-07-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemasite', '0004_auto_20230702_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmshowtime',
            name='priceperseat',
            field=models.IntegerField(verbose_name='Price per seat'),
        ),
        migrations.AlterField(
            model_name='filmshowtime',
            name='totnumofseats',
            field=models.IntegerField(verbose_name='Total number of seats'),
        ),
    ]
