# Generated by Django 3.2.19 on 2023-07-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemasite', '0004_alter_booking_numoftickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.TimeField(max_length=10),
        ),
    ]
