# Generated by Django 3.2.19 on 2023-07-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemasite', '0005_alter_booking_snacks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='cost',
            field=models.FloatField(),
        ),
    ]
