# Generated by Django 3.2.19 on 2023-07-12 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinemasite', '0005_alter_booking_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmshowtime',
            name='totnumofseats',
        ),
    ]
