# Generated by Django 3.2.19 on 2023-07-03 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinemasite', '0006_auto_20230703_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmshowtime',
            name='filmimage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filmimage', to='cinemasite.film', verbose_name='Film image'),
        ),
        migrations.AlterField(
            model_name='filmshowtime',
            name='filmtitle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filmtitle', to='cinemasite.film', verbose_name='Film title'),
        ),
    ]
