# Generated by Django 3.2.19 on 2023-06-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemasite', '0007_auto_20230627_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='film',
        ),
        migrations.AddField(
            model_name='genre',
            name='film',
            field=models.ManyToManyField(to='cinemasite.Film'),
        ),
    ]
