# Generated by Django 3.2.19 on 2023-07-03 13:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinemasite', '0007_auto_20230703_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmshowtime',
            name='filmimage',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
