# Generated by Django 3.2.19 on 2023-07-03 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinemasite', '0008_alter_filmshowtime_filmimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmshowtime',
            name='filmruntime',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filmruntime', to='cinemasite.film', verbose_name='Runtime'),
        ),
    ]
