# Generated by Django 3.2.19 on 2023-06-27 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinemasite', '0009_auto_20230627_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='genre',
        ),
    ]
