# Generated by Django 3.2.19 on 2023-07-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemasite', '0010_remove_filmshowtime_filmruntime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snack',
            name='price',
            field=models.FloatField(),
        ),
    ]
