# Generated by Django 3.2.19 on 2023-06-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemasite', '0013_alter_genre_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
