# Generated by Django 3.2.19 on 2023-06-27 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinemasite', '0015_alter_film_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='description',
            field=models.TextField(unique=True),
        ),
        migrations.CreateModel(
            name='FilmShowtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('num_of_seats', models.IntegerField()),
                ('price_per_seat', models.IntegerField()),
                ('film_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinemasite.film')),
            ],
        ),
    ]
