# Generated by Django 3.2.19 on 2023-06-27 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemasite', '0016_auto_20230627_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='filmshowtime',
            old_name='num_of_seats',
            new_name='tot_num_of_seats',
        ),
    ]
